### ISSUE TITLE
no directory /content/ or /object_detection/

### ISSUE THREAD

**Issue by TaeheeJeong** [vijendra1125/Custom-Mask-RCNN-using-Tensorfow-Object-detection-API#23]
where is /content/ directory?

%cd /content/models/research
%set_env PYTHONPATH=/content/models/research:/content/models/research/slim
PATH_TO_FROZEN_GRAPH = '/content/drive/learning/DL/projects/object_detection/multiple_object_mask/IG/frozen_inference_graph.pb'
PATH_TO_LABELS = '/content/drive/learning/DL/projects/object_detection/multiple_object_mask/dataset/label.pbtxt'

!protoc object_detection/protos/*.proto --python_out=.
!python object_detection/builders/model_builder_test.py
from object_detection.utils import ops as utils_ops
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util

**Comment by vijendra1125** [comment]
the path needs to start with "content" if you want to give the path of a file in gdrive.  If you are not using gdrive then you need content in the path.
