### ISSUE TITLE
Great Explanation!!

### ISSUE THREAD

**Issue by agitcelik** [vijendra1125/Custom-Mask-RCNN-using-Tensorfow-Object-detection-API#8]
Hi Vijendra Singh,

Your project gave me a lot of idea about how to customize R-CNN on my project; therefore, I wanted to mention that.

I may share with you after project done.

Thank you so much for that kind of sharing.

**Comment by vijendra1125** [comment]
Hi Agit, 
I am glad to know that this project helped you but please don't create an issue to mention so. You could write me direct mail for such a thing. :)
All the best for your project. Looking forward to see the result of your project, you could share it with me on vijendrasingh003@gmail.com
